- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      cd ~/new-rep
      git pull origin main
      npm install
      pm2 restart my-app || pm2 start app.js --name my-app
      echo "Node app deployed successfully"
